### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by etatara** [Repast/repast4py#58]
Trying to compile on Windows 10 without WSL.

Development environment:

* Microsoft MPI runtime and SDK https://www.microsoft.com/en-us/download/details.aspx?id=105289
  * Provides mpiexec and libs
* Build Tools https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022
  * Provides command line MS compilers

**Comment by etatara** [comment]
Some unit tests are not passing in Windows 

```
FAILED (errors=1)
Traceback (most recent call last):
  File "L:\repast4py\tests\ctopo_tests.py", line 81, in test_local_bounds_4x2_sticky
    comm = MPI.COMM_WORLD.Create_group(new_group)
  File "mpi4py\MPI\Comm.pyx", line 186, in mpi4py.MPI.Comm.Create_group
NotImplementedError
FAILED (errors=1)
```

**Comment by etatara** [comment]
Trying the Intel One API Tookit:

https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html#gs.5kou46

**Comment by etatara** [comment]
![image](https://github.com/Repast/repast4py/assets/11462868/69c7db4d-347a-4950-b1de-e9abb784ca8a)

**Comment by etatara** [comment]
https://pypi.org/project/mpi4py/#install

**Comment by etatara** [comment]
The mpi4py wheel from pypi is built against MSMPI.  Some of the MPI functions like MPI_Comm_create_group used by repast4py are not implemented in MSMPI, so mpi4py would need to be custom build against an appropriate MPI implementation such as openMPI or IntelMPI.

**Comment by etatara** [comment]
MPI_Comm_create_group() is only used in unit tests, so perhaps we can rewrite and use something like MPI_Comm_create() which appears to be nearly the same and does work with MSMPI.

**Comment by etatara** [comment]
With MSMPI and building repast4py on Windows 10, all unit single process tests pass using 
`python -m unittest discover tests` 

with torch==2.1.0

**Comment by etatara** [comment]
Replacing MPI.COMM_WORLD.Create_group() with MPI.COMM_WORLD.Create() almost all (except one) multiprocess unit tests are passing with MSMPI on Windows 10.

**Comment by etatara** [comment]
The windows_build branch is passing all tests and the ci-build workflow is producing Windows wheels that have been manually tested.  Move to close this issue and merge windows_build into develop after the next code review.
