### ISSUE TITLE
Unit tests fail with latest torch 2.2.0

### ISSUE THREAD

**Issue by etatara** [Repast/repast4py#59]
On both linux and Windows 10, if using torch 2.2.0, the single process unit tests will fail (see below).  Using torch==2.1.0, the unit tests will pass.

```
L:\repast4py>python -m unittest discover tests
..................................EEEE
======================================================================
ERROR: test_accesors (test_value_layer.ValueLayerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "L:\repast4py\tests\test_value_layer.py", line 191, in test_accesors
    self.assertEqual(0.2, vl.get(pt))
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 819, in _baseAssertEqual
    if not first == second:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_borders (test_value_layer.ValueLayerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "L:\repast4py\tests\test_value_layer.py", line 224, in test_borders
    vl.set(pt, 0.2)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\site-packages\repast4py\value_layer.py", line 400, in set
    self.impl.set(pt, val)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\site-packages\repast4py\value_layer.py", line 271, in set
    self.grid[self._update_idx(npt)] = val
IndexError: index 28 is out of bounds for dimension 0 with size 11

======================================================================
ERROR: test_ngh_periodic (test_value_layer.ValueLayerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "L:\repast4py\tests\test_value_layer.py", line 332, in test_ngh_periodic
    self.assertEqual(val, vl.get(dpt(pts[0][i], pts[1][i], 0)))
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 819, in _baseAssertEqual
    if not first == second:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

======================================================================
ERROR: test_ngh_sticky (test_value_layer.ValueLayerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "L:\repast4py\tests\test_value_layer.py", line 270, in test_ngh_sticky
    self.assertEqual(val, vl.get(dpt(pts[0][i], pts[1][i], 0)))
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\eric\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 819, in _baseAssertEqual
    if not first == second:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

----------------------------------------------------------------------
Ran 38 tests in 16.001s

FAILED (errors=4)
```

**Comment by ncollier** [comment]
Also fails with 2.2.1

**Comment by ncollier** [comment]
Fixed in https://github.com/Repast/repast4py/commit/6b8b5d839200d7ff81cc03e2344364707b726372
